### ISSUE TITLE
port to binja plugin API

### ISSUE THREAD

**Issue by lucasduffey** [snare/binja#4]
urls for easy access:

example: https://github.com/Vector35/binaryninja-plugins/tree/master/plugins/official/sample_plugin
https://github.com/Vector35/binaryninja-plugins/ (create an issue when it's done)

**Comment by lucasduffey** [comment]
i was going to do pull request for plugin.json - but trying to figure out how the voltron dependency could easily be resolved in an automated fashion

relevant: https://github.com/Vector35/binaryninja-plugins/issues/4

**Comment by lucasduffey** [comment]
relevant: https://github.com/Vector35/binaryninja-plugins/issues/4

**Comment by snare** [comment]
The dep on the latest GitHub Voltron was just because I hadn't issued a release since I added some stuff to make it easier to write the binjatron plugin. The dep can now be Voltron 0.1.7 as I have issued a new release. I'll update the readme.

**Comment by snare** [comment]
Done in 5ccacf67cfc00bf0081b8304b98eed9bca10803a
